name: 'Tron GitHub'
description: 'Generate Tron Light Cycles animations as SVG files from GitHub contribution data'
author: 'markpython86'

branding:
  icon: 'zap'
  color: 'blue'

inputs:
  github_user_name:
    description: 'GitHub username to generate the Tron animation for'
    required: true
  outputs:
    description: 'List of SVG files to generate (one per line, with optional theme parameter)'
    required: false
    default: |
      tron-light-cycles.svg
      tron-light-cycles-dark.svg?theme=dark
  github-token:
    description: 'GitHub token for authentication (if needed)'
    required: false
    default: ${{ github.token }}

outputs:
  generated-files:
    description: 'List of generated SVG files'

runs:
  using: 'node20'
  main: 'dist/index.js' 