name: Deploy to GitHub Pages and Generate Animation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 12 * * *" # Daily at noon for animation updates

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Generate Live Animation
      run: |
        # Extract username from repository name or use default
        USERNAME=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        echo "Generating animation for user: $USERNAME"
        
        # Create output directory
        mkdir -p dist/animations
        
        # Generate animated SVG from live game capture
        npm run capture "$USERNAME" "dist/animations/tron-github-live.svg"
        
        # Create dark version
        sed 's/#0d1117/#000000/g; s/#161b22/#0d1117/g' dist/animations/tron-github-live.svg > dist/animations/tron-github-live-dark.svg
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
